"""rename metadata to meta_data

Revision ID: 20260109_rename_metadata_to_meta_data
Revises: 20260109_add_checkins_photo_path
Create Date: 2026-01-09 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260109_rename_metadata_to_meta_data'
down_revision = '20260109_add_checkins_photo_path'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_reference_photos', 'metadata', new_column_name='meta_data', existing_type=sa.JSON)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_reference_photos', 'meta_data', new_column_name='metadata', existing_type=sa.JSON)
    # ### end Alembic commands ###
