"""add checkins photo_path

Revision ID: 20260109_add_checkins_photo_path
Revises: 20260109_add_roles_timestamps
Create Date: 2026-01-09 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260109_add_checkins_photo_path'
down_revision = '20260109_add_roles_timestamps'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'photo_path')
    # ### end Alembic commands ###
